# -*- coding: utf-8 -*-
"""streamit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hG4100s5ikqbKZKpOTn-Trod17d0fFmP
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %cd drive/My Drive/PROJECT

!pip install streamlit

# Import necessary libraries
import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np

# Load your trained model
@st.cache(allow_output_mutation=True)
def load_model():
    model = tf.keras.models.load_model('MODEL.h5')
    return model

model = load_model()

# Define a function to make predictions
def predict(image):
    img = tf.image.decode_image(image, channels=3)
    img = tf.image.resize(img, (280, 280))
    img = tf.expand_dims(img, axis=0)
    img = np.array(img) / 255.0  # Normalize pixel values to the range [0, 1]
    pred = model.predict(img)
    return pred

# Streamlit UI
st.title("Brain Tumor Classification")
st.write("Upload an MRI image for classification.")

uploaded_image = st.file_uploader("Choose an MRI image...", type=["jpg", "png", "jpeg"])

if uploaded_image is not None:
    st.image(uploaded_image, caption='Uploaded MRI Image', use_column_width=True)
    image = Image.open(uploaded_image)
    st.write("")
    st.write("Classifying...")

    # Make predictions
    prediction = predict(image)
    class_names = ['Glioma', 'Meningioma','No','Pituitary']  # Replace with your actual class names

    st.write(f"Prediction: {class_names[prediction]}")



